# IMDB Movies Review Dataset

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('imdb_labelled.txt',delimiter='\t',quoting=3)

In [4]:
dataset

Reviews  Label
0    A very, very, very slow-moving, aimless movie ...      0
1    Not sure who was more lost - the flat characte...      0
2    Attempting artiness with black & white and cle...      0
3         Very little music or anything to speak of.        0
4    The best scene in the movie was when Gerardo i...      1
5    The rest of the movie lacks art, charm, meanin...      0
6                                  Wasted two hours.        0
7    Saw the movie today and thought it was a good ...      1
8                                 A bit predictable.        0
9    Loved the casting of Jimmy Buffet as the scien...      1
10                And those baby owls were adorable.        1
11   The movie showed a lot of Florida at it's best...      1
12   The Songs Were The Best And The Muppets Were S...      1
13                                   It Was So Cool.        1
14   This is a very "right on case" movie that deli...      1
15   It had some average acting from the main perso...      0
16   This review is long overdue, since I consider ...      1
17   I'll put this gem up against any movie in term...      1
18   It's practically perfect in all of them – a tr...      1
19   " The structure of this film is easily the mos...      1
20   I can think of no other film where something v...      1
21   In other words, the content level of this film...      1
22   How can anyone in their right mind ask for any...      1
23   It's quite simply the highest, most superlativ...      1
24   Yes, this film does require a rather significa...      1
25       This short film certainly pulls no punches.        0
26   Graphics is far from the best part of the game.        0
27   This is the number one best TH game in the ser...      1
28                          It deserves strong love.        1
29                             It is an insane game.        1
..                                                 ...    ...
970  Enough can not be said of the remarkable anima...      1
971  The art style has the appearance of crayon/pen...      1
972  If you act in such a film, you should be glad ...      0
973  This one wants to surf on the small wave of sp...      0
974  If you haven't choked in your own vomit by the...      0
975  Still, it makes up for all of this with a supe...      1
976  Just consider the excellent story, solid actin...      1
977  Instead, we got a bore fest about a whiny, spo...      0
978  Then I watched it again two Sundays ago (March...      1
979       It is a very well acted and done TV Movie.        1
980  Judith Light is one of my favorite actresses a...      1
981                I keep watching it over and over.        1
982                 It's a sad movie, but very good.        1
983  If you have not seen this movie, I definitely ...      1
984           She is as lovely as usual, this cutie!        1
985  Still it's quite interesting and entertaining ...      1
986                    ;) Recommend with confidence!        1
987  This movie is well-balanced with comedy and dr...      1
988  It was a riot to see Hugo Weaving play a sex-o...      1
989  :) Anyway, the plot flowed smoothly and the ma...      1
990  The opening sequence of this gem is a classic,...      1
991             Fans of the genre will be in heaven.        1
992                Lange had become a great actress.        1
993                It looked like a wonderful story.        1
994            I never walked out of a movie faster.        0
995  I just got bored watching Jessice Lange take h...      0
996  Unfortunately, any virtue in this film's produ...      0
997                   In a word, it is embarrassing.        0
998                               Exceptionally bad!        0
999  All in all its an insult to one's intelligence...      0

[1000 rows x 2 columns]

## Creating the bag of words model`

In [6]:
import re
import nltk

In [7]:
#nltk.download('stopwords') #  Uncomment this line if stopwords is not downloaded
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [8]:
corpus = []
for i in range(dataset.shape[0]):
    review = re.sub('[^A-z]', ' ' ,dataset['Reviews'][i]).lower().split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset['Label']

## Train test Split

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Classification using Gaussian NB model

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB(priors=None)

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.675
[[71 15]
 [50 64]]


## Classification using Decision Tree model

In [33]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=None)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
y_pred = classifier.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.715
[[60 26]
 [31 83]]


## Classification using Random Forest model

In [66]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=120)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=120, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [67]:
y_pred = classifier.predict(X_test)

In [68]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.78
[[68 18]
 [26 88]]


## Classification using Gradient Boosting model

In [114]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(n_estimators=250,learning_rate=0.75)
classifier.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.75, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=250,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [115]:
y_pred = classifier.predict(X_test)

In [116]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.78
[[69 17]
 [27 87]]
