# Amazon Review Dataset

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the dataset

In [13]:
dataset = pd.read_csv('amazon_cells_labelled.txt',delimiter='\t',quoting=3)

In [14]:
dataset

Reviews  Label
0    So there is no way for me to plug it in here i...      0
1                          Good case, Excellent value.      1
2                               Great for the jawbone.      1
3    Tied to charger for conversations lasting more...      0
4                                    The mic is great.      1
5    I have to jiggle the plug to get it to line up...      0
6    If you have several dozen or several hundred c...      0
7          If you are Razr owner...you must have this!      1
8                  Needless to say, I wasted my money.      0
9                     What a waste of money and time!.      0
10                     And the sound quality is great.      1
11   He was very impressed when going from the orig...      1
12   If the two were seperated by a mere 5+ ft I st...      0
13                            Very good quality though      1
14   The design is very odd, as the ear "clip" is n...      0
15   Highly recommend for any one who has a blue to...      1
16                 I advise EVERYONE DO NOT BE FOOLED!      0
17                                    So Far So Good!.      1
18                                       Works great!.      1
19   It clicks into place in a way that makes you w...      0
20   I went on Motorola's website and followed all ...      0
21   I bought this to use with my Kindle Fire and a...      1
22            The commercials are the most misleading.      0
23   I have yet to run this new battery below two b...      1
24   I bought it for my mother and she had a proble...      0
25                Great Pocket PC / phone combination.      1
26   I've owned this phone for 7 months now and can...      1
27   I didn't think that the instructions provided ...      0
28   People couldnt hear me talk and I had to pull ...      0
29                                Doesn't hold charge.      0
..                                                 ...    ...
970  I plugged it in only to find out not a darn th...      0
971                                 Excellent product.      1
972                        Earbud piece breaks easily.      0
973                                     Lousy product.      0
974  This phone tries very hard to do everything bu...      0
975  It is the best charger I have seen on the mark...      1
976                                  SWEETEST PHONE!!!      1
977             :-)Oh, the charger seems to work fine.      1
978  It fits so securely that the ear hook does not...      1
979                                 Not enough volume.      0
980                Echo Problem....Very unsatisfactory      0
981  you could only take 2 videos at a time and the...      0
982                            don't waste your money.      0
983  I am going to have to be the first to negative...      0
984  Adapter does not provide enough charging current.      0
985  There was so much hype over this phone that I ...      0
986  You also cannot take pictures with it in the c...      0
987                            Phone falls out easily.      0
988  It didn't work, people can not hear me when I ...      0
989  The text messaging feature is really tricky to...      0
990  I'm really disappointed all I have now is a ch...      0
991                                Painful on the ear.      0
992                   Lasted one day and then blew up.      0
993                                      disappointed.      0
994                              Kind of flops around.      0
995  The screen does get smudged easily because it ...      0
996  What a piece of junk.. I lose more calls on th...      0
997                       Item Does Not Match Picture.      0
998  The only thing that disappoint me is the infra...      0
999  You can not answer calls with the unit, never ...      0

[1000 rows x 2 columns]

## Creating the bag of words model

In [18]:
import re
import nltk

In [20]:
#nltk.download('stopwords') #  Uncomment this line if stopwords is not downloaded
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [22]:
corpus = []
for i in range(dataset.shape[0]):
    review = re.sub('[^A-z]', ' ' ,dataset['Reviews'][i]).lower().split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset['Label']

## Train test Split

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Classification using Gaussian NB model

In [27]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB(priors=None)

In [28]:
y_pred = classifier.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.72
[[60 36]
 [20 84]]


## Classification using Decision Tree model

In [149]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=20,min_samples_split=0.5)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=20,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=0.5,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [150]:
y_pred = classifier.predict(X_test)

In [151]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.785
[[90  6]
 [37 67]]


## Classification using Random Forest model

In [200]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=22)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=22, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [201]:
y_pred = classifier.predict(X_test)

In [202]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.83
[[86 10]
 [24 80]]


## Classification using Gradient Boosting model

In [321]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(learning_rate=0.675,n_estimators=140,max_depth=10)
classifier.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.675, loss='deviance', max_depth=10,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=140,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [322]:
y_pred = classifier.predict(X_test)

In [323]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.83
[[89  7]
 [27 77]]
